Repository wecode-bootcamp-korea/28-1st-MRMRZR-frontend, pull requests merged in 2022-01, with the labels that each got.

#1 [28기 안현재]Refactor : 네비게이션바 리뷰 반영
  package-lock.json
  src/components/Nav/Dropdown/Dropdown.js
  src/components/Nav/Dropdown/Dropdown.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: Status: 리뷰 요청

#2 [28기 정해수] 메인으로 사용하는 ProductList 구현
  public/data/ProductListData/ProductListData.json
  src/Router.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/components/Product.js
  src/pages/ProductList/components/Product.scss
  src/pages/ProductList/components/SizeFilter.js
  src/pages/ProductList/components/SizeFilter.scss
  src/styles/_variables.scss
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#3 [28기 김선주]Add : Login page, Signup page 기능 구현 중
  src/Router.js
  src/index.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/LogoutButton.js
  src/pages/Login/SignUp.scss
  src/pages/Login/Signup.js
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#4 [28기 안현재] 상품 상세페이지 구현
  src/Router.js
  src/components/Nav/Cart/Cart.js
  src/components/Nav/Cart/Cart.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/ProductDetail/ProductDescription/ProductDescription.js
  src/pages/ProductDetail/ProductDescription/ProductDescription.scss
  src/pages/ProductDetail/ProductDescription/ProductSize/ProductSize.js
  src/pages/ProductDetail/ProductDescription/ProductSize/ProductSize.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductGallery/ProductGallery.js
  src/pages/ProductDetail/ProductGallery/ProductGallery.scss
  src/pages/ProductList/ProductList.js
Labels: Status: 수정 요청
